# Generated by Django 2.2.3 on 2019-07-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('hacker_news_url', models.CharField(max_length=100)),
                ('posted_on', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('upvotes', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
